# Generated by Django 2.1.3 on 2018-12-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
