# Generated by Django 2.1.3 on 2018-12-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cost', models.IntegerField(help_text='In Toman')),
                ('expiration_date', models.DateField()),
                ('rate', models.FloatField()),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Center')),
            ],
        ),
    ]
