# Generated by Django 2.1.3 on 2018-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
