# Generated by Django 2.1.3 on 2018-12-25 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', phone_field.models.PhoneField(default='', help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('رستوران وکافی شاپ', 'رستوران وکافی شاپ'), ('سینما ، کنسرت وتئاتر', 'سینما ، کنسرت وتئاتر'), ('شهربازی', 'شهربازی'), ('مرکز خرید', 'مرکز خرید'), ('مجموعه ورزشی', 'مجموعه ورزشی'), ('پارک وفضای آزاد', 'پارک وفضای آزاد'), ('غیره', 'غیره')], default='STRING', max_length=100)),
                ('ticket_cost', models.IntegerField(help_text='In Toman')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CenterHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('open_time', models.CharField(max_length=100)),
                ('close_time', models.CharField(max_length=100)),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.Center')),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cost', models.IntegerField(help_text='In Toman')),
                ('expiration_date', models.DateField()),
                ('rate', models.IntegerField()),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.Center')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerCenters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centers.Center', unique=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
